<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);

header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Methods: GET, POST, OPTIONS");
header("Access-Control-Allow-Headers: Authorization, x-authorization, X-Authorization, Content-Type");
header("Content-Type: application/json");

if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    http_response_code(200);
    exit;
}

$headers = getallheaders();
require_once "../auth/auth_helper.php";
if (!validateToken()) {
    sendUnauthorized();
}

require_once "../db.php";

$entrenador_id = $_GET['entrenador_id'] ?? null;

if (!$entrenador_id) {
    http_response_code(400);
    echo json_encode(["error" => "entrenador_id es obligatorio"]);
    exit;
}

// SILENT SCHEMA FIX - Ensure columns exist
ob_start(); // Buffer to catch any unintended output
function ensureColumnUsers($conn, $column, $definition) {
    $check = $conn->query("SHOW COLUMNS FROM usuarios LIKE '$column'");
    if ($check && $check->num_rows == 0) {
        $conn->query("ALTER TABLE usuarios ADD `$column` $definition");
    }
}
ensureColumnUsers($conn, 'foto', "VARCHAR(255) NULL");
ensureColumnUsers($conn, 'foto_perfil', "VARCHAR(255) NULL");
ob_clean(); // Discard any text generated by the schema check

$sql = "
SELECT
    u.id AS jugador_id,
    u.nombre AS jugador_nombre,
    u.usuario AS jugador_email,
    u.telefono AS jugador_telefono,
    u.foto,
    u.foto_perfil,
    
    /* NOMBRES DE SUS PACKS UNICOS */
    (
        SELECT GROUP_CONCAT(DISTINCT p1.nombre SEPARATOR ' || ')
        FROM pack_jugadores pj1
        JOIN packs p1 ON pj1.pack_id = p1.id
        LEFT JOIN pack_jugadores_adicionales pja1 ON pj1.id = pja1.pack_jugadores_id AND pja1.jugador_id = u.id
        WHERE p1.entrenador_id = ?
          AND (pj1.jugador_id = u.id OR pja1.estado = 'aceptado')
    ) AS pack_nombres,
    
    /* SESIONES PAGADAS TOTALES (Basado en compras reales) */
    (
        SELECT COALESCE(SUM(p2.sesiones_totales), 0)
        FROM pack_jugadores pj2
        JOIN packs p2 ON pj2.pack_id = p2.id
        WHERE p2.entrenador_id = ?
          AND p2.tipo NOT IN ('grupal', 'pack_grupal', 'clase grupal')
          AND (
            pj2.jugador_id = u.id 
            OR pj2.id IN (SELECT pack_jugadores_id FROM pack_jugadores_adicionales WHERE jugador_id = u.id AND estado = 'aceptado')
            OR (
                pj2.pack_id IN (SELECT r_sub.pack_id FROM reserva_jugadores rj_sub JOIN reservas r_sub ON r_sub.id = rj_sub.reserva_id WHERE rj_sub.jugador_id = u.id AND r_sub.pack_id > 0 AND r_sub.estado != 'cancelado')
                AND pj2.id = (SELECT MIN(id) FROM pack_jugadores WHERE pack_id = p2.id)
                AND p2.id NOT IN (
                    SELECT pj_own.pack_id FROM pack_jugadores pj_own 
                    WHERE pj_own.jugador_id = u.id 
                    OR pj_own.id IN (SELECT pack_jugadores_id FROM pack_jugadores_adicionales WHERE jugador_id = u.id AND estado = 'aceptado')
                )
            )
          )
    ) AS sesiones_pagadas,

    /* SESIONES RESERVADAS FUTURAS (Unicas) de packs individuales */
    (
        SELECT COUNT(DISTINCT r.id)
        FROM reservas r
        JOIN reserva_jugadores rj ON r.id = rj.reserva_id
        LEFT JOIN packs ptr ON r.pack_id = ptr.id
        WHERE rj.jugador_id = u.id
          AND r.entrenador_id = ?
          AND r.estado != 'cancelado'
          AND r.pack_id > 0
          AND (ptr.id IS NULL OR ptr.tipo NOT IN ('grupal', 'pack_grupal', 'clase grupal'))
    ) AS sesiones_reservadas,

    /* TOTAL GRUPALES */
    (
        SELECT COUNT(DISTINCT r3.id) 
        FROM reservas r3
        JOIN reserva_jugadores rj3 ON r3.id = rj3.reserva_id
        WHERE rj3.jugador_id = u.id 
          AND r3.entrenador_id = ? 
          AND r3.estado != 'cancelado'
          AND (r3.tipo = 'grupal' OR r3.tipo = 'pack_grupal' OR r3.tipo = 'clase grupal')
    ) AS sesiones_grupales,

    /* CLASES PENDIENTES (Suma Pagadas - Pasadas, solo sobre individuales) */
    (
        COALESCE((
            SELECT SUM(p4.sesiones_totales)
            FROM pack_jugadores pj4
            JOIN packs p4 ON pj4.pack_id = p4.id
            WHERE p4.entrenador_id = ?
              AND p4.tipo NOT IN ('grupal', 'pack_grupal', 'clase grupal')
              AND (
                pj4.jugador_id = u.id 
                OR pj4.id IN (SELECT pack_jugadores_id FROM pack_jugadores_adicionales WHERE jugador_id = u.id AND estado = 'aceptado')
                OR (
                    pj4.pack_id IN (SELECT r_sub.pack_id FROM reserva_jugadores rj_sub JOIN reservas r_sub ON r_sub.id = rj_sub.reserva_id WHERE rj_sub.jugador_id = u.id AND r_sub.pack_id > 0 AND r_sub.estado != 'cancelado')
                    AND pj4.id = (SELECT MIN(id) FROM pack_jugadores WHERE pack_id = p4.id)
                    AND p4.id NOT IN (
                        SELECT pj_own.pack_id FROM pack_jugadores pj_own 
                        WHERE pj_own.jugador_id = u.id 
                        OR pj_own.id IN (SELECT pack_jugadores_id FROM pack_jugadores_adicionales WHERE jugador_id = u.id AND estado = 'aceptado')
                    )
                )
              )
        ), 0) - 
        (
            SELECT COUNT(DISTINCT r5.id)
            FROM reservas r5
            JOIN reserva_jugadores rj5 ON r5.id = rj5.reserva_id
            LEFT JOIN packs ptr5 ON r5.pack_id = ptr5.id
            WHERE rj5.jugador_id = u.id
              AND r5.entrenador_id = ?
              AND r5.estado != 'cancelado'
              AND r5.pack_id > 0
              AND (ptr5.id IS NULL OR ptr5.tipo NOT IN ('grupal', 'pack_grupal', 'clase grupal'))
              AND (r5.fecha < CURDATE() OR (r5.fecha = CURDATE() AND r5.hora_fin <= CURTIME()))
        )
    ) AS sesiones_pendientes

FROM usuarios u
WHERE u.id IN (
    SELECT DISTINCT pj_sub.jugador_id FROM pack_jugadores pj_sub 
    JOIN packs p_sub ON p_sub.id = pj_sub.pack_id WHERE p_sub.entrenador_id = ?
) OR u.id IN (
    SELECT DISTINCT rj_sub.jugador_id FROM reserva_jugadores rj_sub 
    JOIN reservas r_sub ON r_sub.id = rj_sub.reserva_id WHERE r_sub.entrenador_id = ? AND r_sub.estado != 'cancelado'
) OR u.id IN (
    SELECT DISTINCT ea_sub.alumno_id FROM entrenador_alumno ea_sub WHERE ea_sub.entrenador_id = ?
)
GROUP BY u.id
ORDER BY u.nombre ASC
";

$stmt = $conn->prepare($sql);
$stmt->bind_param("iiiiiiiii", $entrenador_id, $entrenador_id, $entrenador_id, $entrenador_id, $entrenador_id, $entrenador_id, $entrenador_id, $entrenador_id, $entrenador_id);
$stmt->execute();

$result = $stmt->get_result();
$data = [];

while ($row = $result->fetch_assoc()) {
    // Ensure numbers are numeric and non-negative
    $row['sesiones_pagadas'] = (int)$row['sesiones_pagadas'];
    $row['sesiones_reservadas'] = (int)$row['sesiones_reservadas'];
    $row['sesiones_grupales'] = (int)$row['sesiones_grupales'];
    $row['sesiones_pendientes'] = max(0, (int)$row['sesiones_pendientes']);
    
    // For internal frontend compatibility
    $row['sesiones_restantes'] = $row['sesiones_pendientes'];
    $row['creditos_reales'] = $row['sesiones_pendientes'];
    $row['pack_nombre'] = $row['pack_nombres'] ?: 'Sin Pack';
    
    $data[] = $row;
}

echo json_encode($data, JSON_UNESCAPED_UNICODE);
$conn->close();
