<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);

header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Methods: GET, POST, OPTIONS");
header("Access-Control-Allow-Headers: Authorization, Content-Type");
header("Content-Type: application/json");

if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    http_response_code(200);
    exit;
}

$headers = getallheaders();
require_once "../auth/auth_helper.php";
if (!validateToken()) {
    sendUnauthorized();
}

require_once "../db.php";

$entrenador_id = $_GET['entrenador_id'] ?? null;

if (!$entrenador_id) {
    http_response_code(400);
    echo json_encode(["error" => "entrenador_id es obligatorio"]);
    exit;
}

// SILENT SCHEMA FIX - Ensure columns exist
ob_start(); // Buffer to catch any unintended output
function ensureColumnUsers($conn, $column, $definition) {
    $check = $conn->query("SHOW COLUMNS FROM usuarios LIKE '$column'");
    if ($check && $check->num_rows == 0) {
        $conn->query("ALTER TABLE usuarios ADD `$column` $definition");
    }
}
ensureColumnUsers($conn, 'foto', "VARCHAR(255) NULL");
ensureColumnUsers($conn, 'foto_perfil', "VARCHAR(255) NULL");
ob_clean(); // Discard any text generated by the schema check

$sql = "
SELECT
    u.id AS jugador_id,
    u.nombre AS jugador_nombre,
    u.usuario AS jugador_email,
    u.telefono AS jugador_telefono,
    u.foto,
    u.foto_perfil,
    
    /* SESIONES PAGADAS (Solo packs individuales) */
    (
        SELECT COALESCE(SUM(p2.sesiones_totales), 0)
        FROM pack_jugadores pj2
        JOIN packs p2 ON p2.id = pj2.pack_id
        WHERE pj2.jugador_id = u.id 
          AND p2.entrenador_id = ?
          AND p2.tipo NOT IN ('grupal', 'pack_grupal')
    ) AS sesiones_pagadas,

    /* SESIONES RESERVADAS (Solo individuales, Pasadas + Futuras) */
    (
        SELECT COUNT(DISTINCT r.id)
        FROM reservas r
        JOIN reserva_jugadores rj ON r.id = rj.reserva_id
        WHERE rj.jugador_id = u.id
          AND r.entrenador_id = ?
          AND r.estado != 'cancelado'
          AND r.tipo NOT IN ('grupal', 'pack_grupal')
    ) AS sesiones_reservadas,

    /* TOTAL GRUPALES (All-time group sessions) */
    (
        SELECT COUNT(DISTINCT r.id) 
        FROM reservas r
        JOIN reserva_jugadores rj ON r.id = rj.reserva_id
        WHERE rj.jugador_id = u.id 
          AND r.entrenador_id = ? 
          AND r.estado != 'cancelado'
          AND (r.tipo = 'grupal' OR r.tipo = 'pack_grupal')
    ) AS sesiones_grupales,

    /* CLASES PENDIENTES (Total Individuales - Pasadas Individuales) */
    (
        (
            SELECT COALESCE(SUM(p3.sesiones_totales), 0)
            FROM pack_jugadores pj3
            JOIN packs p3 ON p3.id = pj3.pack_id
            WHERE pj3.jugador_id = u.id 
              AND p3.entrenador_id = ?
              AND p3.tipo NOT IN ('grupal', 'pack_grupal')
        ) - 
        (
            SELECT COUNT(DISTINCT r4.id)
            FROM reservas r4
            JOIN reserva_jugadores rj4 ON r4.id = rj4.reserva_id
            WHERE rj4.jugador_id = u.id
              AND r4.entrenador_id = ?
              AND r4.estado != 'cancelado'
              AND r4.tipo NOT IN ('grupal', 'pack_grupal')
              AND (r4.fecha < CURDATE() OR (r4.fecha = CURDATE() AND r4.hora_fin <= CURTIME()))
        )
    ) AS sesiones_pendientes

FROM usuarios u
WHERE u.id IN (
    SELECT pj_sub.jugador_id FROM pack_jugadores pj_sub 
    JOIN packs p_sub ON p_sub.id = pj_sub.pack_id WHERE p_sub.entrenador_id = ?
) OR u.id IN (
    SELECT rj_sub.jugador_id FROM reserva_jugadores rj_sub 
    JOIN reservas r_sub ON r_sub.id = rj_sub.reserva_id WHERE r_sub.entrenador_id = ? AND r_sub.estado != 'cancelado'
)
GROUP BY u.id
ORDER BY u.nombre ASC
";

$stmt = $conn->prepare($sql);
$stmt->bind_param("iiiiiii", $entrenador_id, $entrenador_id, $entrenador_id, $entrenador_id, $entrenador_id, $entrenador_id, $entrenador_id);
$stmt->execute();

$result = $stmt->get_result();
$data = [];

while ($row = $result->fetch_assoc()) {
    // Ensure numbers are numeric and non-negative
    $row['sesiones_pagadas'] = (int)$row['sesiones_pagadas'];
    $row['sesiones_reservadas'] = (int)$row['sesiones_reservadas'];
    $row['sesiones_grupales'] = (int)$row['sesiones_grupales'];
    $row['sesiones_pendientes'] = max(0, (int)$row['sesiones_pendientes']);
    
    // For internal frontend compatibility
    $row['sesiones_restantes'] = $row['sesiones_pendientes'];
    
    $data[] = $row;
}

echo json_encode($data, JSON_UNESCAPED_UNICODE);
$conn->close();
